### ISSUE TITLE
App crashes when an operator is click twice

### ISSUE THREAD

**Issue by bolah2009** [adriaanbd/reagir_calculator#8]
## Current behaviour:
App crashes when an operator button is clicked more than once when `next` is still `undefined`

![calcerr](https://user-images.githubusercontent.com/36057474/71166840-cde22000-2253-11ea-8db0-fa01d2108b4e.gif)

## Expected behaviour:

When an operator is clicked more consecutively, only the operator state should change to the most recent without any operation been carried out. This means the `operate` function on line 42 shouldn't execute since `Big(null)` or `Big(undefined)` in `operate.js` with throw an error.

### Steps to reproduce:

Click on an operator button multiple times

**Comment by adriaanbd** [comment]
Fixed, thank you
